name: NeuroPerformanceDubai
favicon: null
layout_spectrum: 0.20047437818720937
typography_spectrum: 0.488580982433632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9932864110451192
  lightness: 0.08338111825287342
  saturation: 0.5069172927178442
  rhythmicContrast: 0.6504778338130563
purpose: []
